#ifndef ALIGNMENT_H_
#define ALIGNMENT_H_

#include "inclusions.hpp"

enum Alignment {
    LAWFULGOOD,     NEUTRALGOOD,    CHAOTICGOOD,
    LAWFULNEUTRAL,  TRUENEUTRAL,    CHAOTICNEUTRAL,
    LAWFULEVIL,     NEUTRALEVIL,    CHAOTICEVIL,
    UNALIGNED
};

#endif // ALIGNMENT_H_